rabus_twitter_signin_authenticate:
    pattern: /authenticate
    defaults: { _controller: rabus.twitter.sign_in_controller:authenticate }

rabus_twitter_signin_callback:
    pattern: /callback
    defaults: { _controller: rabus.twitter.sign_in_controller:callback }
