services:
    rabus.twitter.api_gateway:
        class: Rabus\Bundle\Twitter\SignInBundle\Service\TwitterApiGateway
        arguments: [@rabus.twitter.oauth]
    rabus.twitter.sign_in_controller:
        class: Rabus\Bundle\Twitter\SignInBundle\Controller\TwitterSignInController
        arguments: [@rabus.twitter.api_gateway, @router]
